import path from 'node:path';
import { writeText } from './fs-utils.js';
import { pascalCase } from './names.js';
import { loadProjectSchema } from './schema.js';

export async function generateTypes(config, options = {}) {
  const project = options.project ?? await loadProjectSchema(config);
  const content = renderTypes(project.resources, config);
  const outFiles = outputFiles(config, options);

  for (const outFile of outFiles) {
    await writeText(outFile, content);
  }

  return {
    content,
    outFiles,
    diagnostics: project.diagnostics,
  };
}

export function renderTypes(resources, config) {
  const lines = [
    '/* eslint-disable */',
    '// This file is generated by json-fixture-db. Do not edit by hand.',
    '',
  ];

  const enumAliases = collectEnumAliases(resources);
  for (const alias of enumAliases) {
    lines.push(`export type ${alias.name} = ${alias.values.map((value) => literalType(value)).join(' | ')};`, '');
  }

  for (const resource of resources) {
    if (resource.description && config.types?.emitComments !== false) {
      lines.push(jsDoc(resource.description));
    }

    lines.push(`export type ${resource.typeName} = {`);
    for (const [fieldName, field] of Object.entries(resource.fields)) {
      const fieldLines = renderField(fieldName, field, resource, config, 1);
      lines.push(...fieldLines);
    }
    lines.push('};', '');
  }

  const collectionResources = resources.filter((resource) => resource.kind === 'collection');
  const documentResources = resources.filter((resource) => resource.kind === 'document');

  lines.push('export type JsonDbCollections = {');
  for (const resource of collectionResources) {
    lines.push(`  ${propertyName(resource.name)}: ${resource.typeName};`);
  }
  lines.push('};', '');

  lines.push('export type JsonDbDocuments = {');
  for (const resource of documentResources) {
    lines.push(`  ${propertyName(resource.name)}: ${resource.typeName};`);
  }
  lines.push('};', '');

  lines.push('export type JsonDbTypes = {');
  lines.push('  collections: JsonDbCollections;');
  lines.push('  documents: JsonDbDocuments;');
  lines.push('};');

  if (config.types?.exportRuntimeHelpers !== false) {
    lines.push('', 'export type JsonDbCollectionName = keyof JsonDbCollections;', 'export type JsonDbDocumentName = keyof JsonDbDocuments;');
  }

  return `${lines.join('\n')}\n`;
}

function outputFiles(config, options) {
  const outFiles = [];
  if (options.outFile) {
    outFiles.push(path.resolve(config.cwd, options.outFile));
    return unique(outFiles);
  }

  if (config.types?.outFile) {
    outFiles.push(config.types.outFile);
  }

  if (config.types?.commitOutFile) {
    outFiles.push(config.types.commitOutFile);
  }

  return unique(outFiles);
}

function renderField(fieldName, field, resource, config, depth) {
  const lines = [];
  const indent = '  '.repeat(depth);

  if (field.description && config.types?.emitComments !== false) {
    lines.push(`${indent}${jsDoc(field.description, depth)}`);
  }

  const readonly = config.types?.useReadonly ? 'readonly ' : '';
  const optional = field.required ? '' : '?';
  lines.push(`${indent}${readonly}${propertyName(fieldName)}${optional}: ${typeForField(field, fieldName, resource, config, depth)};`);

  return lines;
}

function typeForField(field, fieldName, resource, config, depth) {
  switch (field.type) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'enum':
      return enumAliasName(resource, fieldName);
    case 'array':
      return `Array<${typeForField(field.items ?? { type: 'unknown' }, `${fieldName}Item`, resource, config, depth)}>`;
    case 'object':
      return objectType(field, resource, config, depth);
    case 'unknown':
    default:
      return 'unknown';
  }
}

function objectType(field, resource, config, depth) {
  const fields = field.fields ?? {};
  const entries = Object.entries(fields);

  if (entries.length === 0) {
    return 'Record<string, unknown>';
  }

  const indent = '  '.repeat(depth);
  const childIndent = '  '.repeat(depth + 1);
  const readonly = config.types?.useReadonly ? 'readonly ' : '';
  const lines = ['{'];
  for (const [fieldName, childField] of entries) {
    if (childField.description && config.types?.emitComments !== false) {
      lines.push(`${childIndent}${jsDoc(childField.description, depth + 1)}`);
    }

    const optional = childField.required ? '' : '?';
    lines.push(`${childIndent}${readonly}${propertyName(fieldName)}${optional}: ${typeForField(childField, fieldName, resource, config, depth + 1)};`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

function collectEnumAliases(resources) {
  const aliases = [];
  for (const resource of resources) {
    for (const [fieldName, field] of Object.entries(resource.fields)) {
      collectFieldEnumAliases(aliases, resource, fieldName, field);
    }
  }
  return aliases;
}

function collectFieldEnumAliases(aliases, resource, fieldName, field) {
  if (field.type === 'enum') {
    aliases.push({
      name: enumAliasName(resource, fieldName),
      values: field.values ?? [],
    });
  }

  if (field.type === 'object') {
    for (const [childName, childField] of Object.entries(field.fields ?? {})) {
      collectFieldEnumAliases(aliases, resource, `${fieldName}${pascalCase(childName)}`, childField);
    }
  }

  if (field.type === 'array' && field.items) {
    collectFieldEnumAliases(aliases, resource, `${fieldName}Item`, field.items);
  }
}

function enumAliasName(resource, fieldName) {
  return `${resource.typeName}${pascalCase(fieldName)}`;
}

function literalType(value) {
  return JSON.stringify(value);
}

function propertyName(value) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function jsDoc(text, depth = 0) {
  const indent = '  '.repeat(depth);
  const escaped = String(text).replaceAll('*/', '* /');
  return `${indent}/** ${escaped} */`.trimStart();
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}
